language: node_js

addons:
  chrome: stable

node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

after_success:
  cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js